# Generated by Django 3.2.3 on 2021-08-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System_Web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bmw',
            options={'managed': False},
        ),
    ]
